"""
Generate reports/nhanes/CLAIMS.md from the saved metrics, so every number and
character count in the claims sheet is exact and reproducible.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO))

from src.nhanes.constants import REPORTS_DIR  # noqa: E402
from src.nhanes.features import feature_inventory  # noqa: E402

LIMIT = 150


def main() -> None:
    t = json.loads((REPORTS_DIR / "test_metrics.json").read_text())
    e2 = json.loads((REPORTS_DIR / "external_metrics.json").read_text())
    c = json.loads((REPORTS_DIR / "cohort_summary.json").read_text())
    v3_path = REPORTS_DIR / "external_metrics_v3.json"
    e3 = json.loads(v3_path.read_text()) if v3_path.exists() else None
    inv = feature_inventory()

    B, E = inv["n_blood_tests"], inv["n_engineered_scores"]
    N = c["final_n"]
    NK = N // 1000
    fin = t["models"][t["final_model"]]
    X, lo, hi = fin["roc_auc"]["auc"], fin["roc_auc"]["ci_low"], fin["roc_auc"]["ci_high"]
    XE, elo, ehi = (fin["early_subgroup"]["roc_auc"][k] for k in ("auc", "ci_low", "ci_high"))
    y2 = e2["by_sex_assumption"]["male"]["roc_auc"]
    Y2, y2lo, y2hi = y2["auc"], y2["ci_low"], y2["ci_high"]
    if e3 is not None:
        f3 = e3["models"][e3["final_model"]]
        y3 = f3["uci"]["male"]["roc_auc"]
        Y, ylo, yhi = y3["auc"], y3["ci_low"], y3["ci_high"]
        y_desc = (f"ROC-AUC of the v3 transfer model ({f3['family']}, 14 shared features, trained on NHANES only, "
                  f"selected by NHANES CV) on the 399 UCI hospital patients, eGFR computed as male; 95% CI "
                  f"[{ylo:.2f}, {yhi:.2f}]. This is a disclosed SECOND look at UCI; the first look "
                  f"(v2 harmonised logistic) was {Y2:.2f} [{y2lo:.2f}, {y2hi:.2f}]")
    else:
        Y, ylo, yhi = Y2, y2lo, y2hi
        y_desc = (f"ROC-AUC of the 14-feature logistic variant, trained on NHANES only, applied unchanged to the "
                  f"399 UCI hospital patients (eGFR computed as male; 95% CI [{ylo:.2f}, {yhi:.2f}])")

    egfr_missed = c["overall"]["n_ckd_early_subgroup"] / c["overall"]["n_ckd"]
    user_line = (f"Built CKD ML pipeline on {NK}K adults; engineered eGFR + {B} biomarkers; achieved {X:.2f} AUC; "
                 f"showed eGFR missed {egfr_missed:.0%} of CKD; tested on 399 hospital cases")

    def mk(s: str) -> str:
        return f"```\n{s}\n```\n{len(s)} characters" + ("" if len(s) <= LIMIT else f"  **OVER {LIMIT}**")

    template = (f"Built ML model flagging early CKD from {B} routine blood tests + {E} self-built kidney scores; "
                f"{NK}K adults, {X:.2f} AUC; {Y:.2f} AUC on 399 hospital patients")
    alt1 = (f"Built ML model flagging CKD from {B} routine blood tests + {E} derived kidney scores; "
            f"{NK}K US adults, {X:.2f} AUC ({XE:.2f} early-stage); {Y:.2f} on 399 patients")
    alt2 = (f"Built ML model flagging CKD from {B} routine blood tests + {E} derived kidney scores; "
            f"{NK}K US adults, {X:.2f} AUC ({XE:.2f} early-stage, no urine test)")
    alt3 = (f"Built CKD screening model from {B} routine blood tests + {E} derived kidney scores; "
            f"{NK}K US adults (CDC NHANES), {X:.2f} held-out AUC, {XE:.2f} early-stage")

    md = f"""# Claims sheet (Common App activity line)

Generated by `scripts/nhanes_12_claims.py` from `cohort_summary.json`, `test_metrics.json`,
`external_metrics.json`{' and `external_metrics_v3.json`' if e3 else ''}; character counts are exact.

## The line as requested (template filled with the real numbers)

{mk(template)}

| token | value | exactly what it measures |
|---|---|---|
| B = {B} | routine blood tests | distinct blood analytes used as features: {', '.join(inv['blood_tests'])} (three standard panels: metabolic panel, CBC, HbA1c) |
| E = {E} | engineered kidney scores | {' and '.join(inv['engineered_scores'])}: the CKD-EPI 2021 eGFR equation and the BUN:creatinine ratio, implemented in `src/features/derive.py` / `src/nhanes/egfr.py` |
| N = {NK}K | adults | {N:,} NHANES 2005-Mar 2020 participants aged >= 18, not pregnant, with creatinine and urine ACR measured (rounded down to thousands) |
| X = {X:.2f} | held-out AUC | ROC-AUC of the final gradient-boosting model on the 8,038 participants of the 2017-Mar 2020 cycle, never used for training or tuning; 95% CI [{lo:.2f}, {hi:.2f}] |
| Y = {Y:.2f} | external AUC | {y_desc} |

## Your line, verified claim by claim

{mk(user_line)}

| claim | what backs it | status |
|---|---|---|
| "Built CKD ML pipeline on {NK}K adults" | {N:,} NHANES adults after the four cohort filters (`cohort_flow.md`) | supported |
| "engineered eGFR + {B} biomarkers" | eGFR computed as a feature with the CKD-EPI 2021 equation (`src/nhanes/egfr.py`); {B} blood analytes as features (`src/nhanes/constants.py::BLOOD_TEST_FEATURES`) | supported; eGFR is a published equation you implemented, so "engineered" means feature engineering, not a new score |
| "achieved {X:.2f} AUC" | {X:.3f} [{lo:.3f}, {hi:.3f}] on the held-out 2017-Mar 2020 cycle, model frozen before the test (`test_metrics.json`) | supported |
| "showed eGFR missed {egfr_missed:.0%} of CKD" | {c['overall']['n_ckd_early_subgroup']:,} of {c['overall']['n_ckd']:,} CKD cases ({egfr_missed:.1%}) had eGFR >= 60 and were CKD only by urine albumin (KDIGO G1-G2 A2-A3); eGFR alone scores AUC 0.556 in that subgroup (`cohort_summary.json`, `test_metrics.json`) | supported; it describes the standard eGFR < 60 screen, not your model |
| "tested on 399 hospital cases" | external validation on the 399 UCI patients: first look {Y2:.2f}, second look after a pre-specified fix {Y:.2f} (`external_metrics.json`, `external_metrics_v3.json`) | supported; if you add a number, both must be cited together |

## Wording the results do not fully support

1. **"early CKD" next to {X:.2f}.** The {X:.2f} is for all-stage CKD (eGFR < 60 OR ACR >= 30) and eGFR is
   both a feature and half of that label, so part of {X:.2f} is definitional. Measured early-stage
   performance (test participants with eGFR >= 60, where CKD can only be albuminuria) is
   **{XE:.2f} AUC [{elo:.2f}, {ehi:.2f}]**: real signal, well above the eGFR-only baseline (0.56), but
   moderate. "Early" is justified only with {XE:.2f} next to it; {X:.2f} as an "early CKD" result overstates.
2. **"{Y:.2f} AUC on 399 hospital patients."** {'This is the v3 transfer model after a disclosed second look at UCI: the first-look v2 result was ' + f'{Y2:.2f}' + '. Both must appear in any write-up; the line may quote ' + f'{Y:.2f}' + ' only if the project materials state that the external set was revisited once after a pre-specified fix of a diagnosed preprocessing flaw (no tuning on UCI).' if e3 else 'Accurate but weak (CI ' + f'{ylo:.2f}-{yhi:.2f}' + '); consider leaving it out of the line.'} It is also a 14-feature model, not the {X:.2f} model.
3. **"self-built kidney scores."** eGFR and the BUN:creatinine ratio are standard clinical formulas that
   you implemented and validated, not scores you invented. "Derived" or "computed" is accurate.
4. **"routine blood tests"** is supported: all {B} analytes come from a metabolic panel, a CBC and an
   HbA1c. "17 blood tests" is defensible (17 distinct analytes); "3 routine blood panels" is more conservative.
5. **"{NK}K adults"**: say "{NK}K US adults" if space allows; the data are a US national survey.

## Honest alternative lines (all <= {LIMIT} characters unless marked)

{mk(alt1)}
Keeps every number, names the early-stage AUC explicitly, drops "early" from the headline claim.

{mk(alt2)}
No external claim; the strongest line that needs no footnote.

{mk(alt3)}
Names the data source; no external claim.

## Recommended line

{mk(alt1 if len(alt1) <= LIMIT else alt2)}

Use the external number only together with the disclosure above (first look {Y2:.2f}, second look after a
pre-specified fix {Y:.2f}); the additional-information section is the place for that sentence.
"""
    (REPORTS_DIR / "CLAIMS.md").write_text(md)
    for name, s in [("user_line", user_line), ("template", template), ("alt1", alt1), ("alt2", alt2), ("alt3", alt3)]:
        print(f"{name}: {len(s)} chars{' OK' if len(s) <= LIMIT else ' TOO LONG'}\n  {s}")
    print("CLAIMS.md written")


if __name__ == "__main__":
    main()
